### ISSUE TITLE
Resolvers.txt now missing from agents repo after last commit (bf1440f 2 days ago)

### ISSUE THREAD

**Issue by factuminc** [reconness/reconness-agents#12]
Resolvers.txt is required for docker compose / build and is now missing.

If you inspect the commit below we can see that resolvers.txt is now deleted:
https://github.com/reconness/reconness-agents/commit/bf1440fe8b222d6006f7326fb17b5074379a6721

I can perhaps skip this step or make my own branch but I wanted to point this out in case it was accidentally deleted. Unfortunately other than general DNS resolution I cannot say that I know exactly specifically what the file is for but I can assume that it is for one of the domain related agents.

Anyway, I have been testing out Reconness and it works great. I noticed that this file is missing today when I built a new docker image for reconness.

Cheers. It is a great tool so far. I am still trying to test it out more.

**Comment by gorums** [comment]
Hi @factuminc  check the last [Dockerfile ](https://raw.githubusercontent.com/reconness/reconness-agents/master/Dockerfile)we removed the resolvers.txt too

thanks for the feedback

**Comment by gorums** [comment]
right now we have inside ReconNess a default resolvers.txt, check the doc here

[https://docs.reconness.com/agents/wordlists](https://docs.reconness.com/agents/wordlists)
