### ISSUE TITLE
old Amass version results in failed docker build

### ISSUE THREAD

**Issue by kslosek** [reconness/reconness-agents#4]
I'm just trying this out and I really love it!  I used the example Dockerfile in this repo and my build failed because the version of Amass is old.  It looks like OWASP has archived the amass release v.3.4.2.  I updated the Dockerfile locally to the latest v.3.5.5 and it built with no errors.

I've never contributed to another person's repo, but I forked the repo made the fix and would be happy to submit a PR for the fix.

Thanks for making this software, I've been looking for something like this for a long time.

**Comment by gorums** [comment]
Hi @kslosek, thanks for the feedback, I'll update amass version ASAP or If you did the update you can send the PR and I'll test and approve it.

Thanks

**Comment by gorums** [comment]
Hey @kslosek, I merged a PR with the amass fix. thanks for the feedback
